import {describe,it,expect} from 'vitest';
import {MAPS as maps} from '../../config/maps';
import {calculate,emptyDraft,exportDraft,fitHorizontal,horizontal,parseDraft,type Pair} from './calibration';
const fixture=():Pair[]=>[[0,0],[100,0],[0,100],[80,75]].map(([x,z],i)=>({id:String(i),x,z,east:2*x-3*z+12,north:3*x+2*z-7,role:'fit'}));
describe('horizontal calibration candidate',()=>{
 it('recovers a known scale, rotation and translation',()=>{const r=fitHorizontal(fixture());expect(r.a).toBeCloseTo(2,10);expect(r.b).toBeCloseTo(3,10);expect(r.eastOffset).toBeCloseTo(12);expect(r.northOffset).toBeCloseTo(-7);expect(r.metersPerUnit).toBeCloseTo(Math.sqrt(13));expect(r.rmse).toBeLessThan(1e-10);});
 it('keeps independent checks outside the fit',()=>{const points=fixture();points.push({...points[0],id:'check',east:15,north:-3,role:'check'});const r=fitHorizontal(points);expect(r.rmse).toBeLessThan(1e-10);expect(r.checkRmse).toBeCloseTo(5);});
 it('reports error for inconsistent measurements',()=>{const points=fixture();points[0].east+=10;expect(fitHorizontal(points).rmse).toBeGreaterThan(1);});
 it('rejects insufficient, collinear, duplicate and invalid controls',()=>{expect(()=>fitHorizontal(fixture().slice(0,2))).toThrow();expect(()=>fitHorizontal(fixture().map(p=>({...p,z:0})))).toThrow();expect(()=>fitHorizontal([...fixture(),fixture()[0]])).toThrow();expect(()=>fitHorizontal(fixture().map(p=>({...p,east:NaN})))).toThrow();});
 it('projects WGS84 origin to zero and respects east and north',()=>{expect(horizontal(0,0,{lat:0,lon:0})).toEqual({east:0,north:0});expect(horizontal(0,.001,{lat:0,lon:0}).east).toBeCloseTo(111.31949,4);expect(horizontal(.001,0,{lat:0,lon:0}).north).toBeCloseTo(110.57428,4);expect(()=>horizontal(91,0,{lat:0,lon:0})).toThrow();expect(()=>horizontal(1,0,{lat:0,lon:0})).toThrow();});
 it('estimates either Z direction without assuming model north',()=>{for(const sign of [1,-1]){const map=maps[0],d=emptyDraft(map);d.points=[[0,0],[0,.001],[.001,0],[.001,.001]].map(([lat,lon],i)=>{const latitude=map.geo.origin.lat+lat,longitude=map.geo.origin.lon+lon,p=horizontal(latitude,longitude,map.geo.origin);return{id:String(i),local:{x:p.east/2,y:0,z:sign*p.north/2},latitude:String(latitude),longitude:String(longitude),source:'SYNTHETIC UNIT TEST ONLY',role:'fit'};});const r=calculate(d,map);expect(r.zSign).toBe(sign);expect(r.metersPerUnit).toBeCloseTo(2);expect(r.rmse).toBeLessThan(1e-8);}});
 it('isolates drafts by map and model frame',()=>{const d=emptyDraft(maps[0]);expect(parseDraft(JSON.stringify(d),maps[0])).toEqual(d);expect(()=>parseDraft(JSON.stringify(d),maps[1])).toThrow();expect(()=>parseDraft(JSON.stringify({...d,frame:'changed'}),maps[0])).toThrow();});
 it('exports incomplete drafts as pending and never calibrated',()=>{const e=exportDraft(emptyDraft(maps[0]),maps[0]);expect(e.candidate).toBeNull();expect(e.fieldCalibrated).toBe(false);expect(e.altitudeReferenceValidated).toBe(false);expect(parseDraft(JSON.stringify(e),maps[0])).toEqual(e.draft);});
 it('rejects malformed import and missing real data',()=>{expect(()=>parseDraft('null',maps[0])).toThrow();expect(()=>parseDraft('{}',maps[0])).toThrow();const d=emptyDraft(maps[0]);d.points=[{id:'a',local:{x:0,y:0,z:0},latitude:'',longitude:'',source:'',role:'fit'}];expect(()=>calculate(d,maps[0])).toThrow(/fonte/);d.points[0].source='test';expect(()=>calculate(d,maps[0])).toThrow(/Preencha/);expect(()=>parseDraft(JSON.stringify({...d,points:[...d.points,...d.points]}),maps[0])).toThrow();});
});

