import {it,expect} from 'vitest';
import {MemorySessionRepository,PersistentSessionRepository,type SessionStore} from './SessionRepository';
import type {RecordedSession} from '../../types/domain';
const session=(id:string,mapId='a',startedAt=1):RecordedSession=>({id,mapId,droneId:'sim',mode:'simulation',mission:{id:'m',mapId,waypoints:[],speed:1,returnToBase:false},frames:[],events:[],startedAt,endedAt:2});
it('retains ten sessions per map and clones stored data',()=>{const r=new MemorySessionRepository();r.save(session('other','b'));for(let i=0;i<12;i++)r.save(session(String(i),'a',i));expect(r.list('a').map(s=>s.id)).toEqual(['2','3','4','5','6','7','8','9','10','11']);expect(r.list('b')).toHaveLength(1);const copy=r.list('a');copy[0].mission.speed=99;expect(r.list('a')[0].mission.speed).toBe(1);});
it('merges saves made during hydration without losing either session',async()=>{let resolve!:(s:RecordedSession[])=>void;const writes:RecordedSession[]=[];const store:SessionStore={load:()=>new Promise(r=>{resolve=r;}),save:async s=>{writes.push(s);}};const r=new PersistentSessionRepository(store);const current=session('new');r.save(current);current.mission.speed=9;resolve([session('old')]);await r.whenSettled();expect(r.list('a')).toHaveLength(2);expect(writes[0].mission.speed).toBe(1);expect(r.status).toBe('saved');});
it('restores sessions in a fresh repository',async()=>{const data:RecordedSession[]=[];const store:SessionStore={load:async()=>structuredClone(data),save:async s=>{data.push(structuredClone(s));}};const first=new PersistentSessionRepository(store);first.save(session('persisted'));await first.whenSettled();const second=new PersistentSessionRepository(store);await second.whenSettled();expect(second.list('a')[0].id).toBe('persisted');expect(second.list('b')).toEqual([]);});
it('keeps replay data and signals failures instead of claiming it was saved',async()=>{const r=new PersistentSessionRepository({load:async()=>[],save:async()=>{throw new Error('quota');}});await r.whenSettled();r.save(session('unsaved'));await r.whenSettled();expect(r.status).toBe('error');expect(r.list('a')[0].id).toBe('unsaved');});
it('reports unavailable storage and supports unsubscribing',async()=>{const r=new PersistentSessionRepository({load:async()=>{throw new Error('denied');},save:async()=>{}});let notifications=0;const off=r.subscribe(()=>notifications++);await r.whenSettled();expect(r.status).toBe('error');expect(notifications).toBe(1);off();r.save(session('a'));await r.whenSettled();expect(notifications).toBe(1);expect(r.status).toBe('error');});
