import {createHash} from 'node:crypto';
export class HttpError extends Error{constructor(status,message){super(message);this.status=status;}}
export class SupabaseService{
 constructor(url,key,fetcher=fetch){if(!url||new URL(url).protocol!=='https:'||!key)throw new Error('Supabase HTTPS e chave pública são obrigatórios.');if(key.startsWith('sb_secret_'))throw new Error('Use chave publishable/anon, nunca service_role.');if(!key.startsWith('sb_publishable_')){let claims;try{claims=JSON.parse(Buffer.from(key.split('.')[1],'base64url').toString());}catch{}if(claims?.role!=='anon')throw new Error('Use chave publishable/anon.');}this.url=url.replace(/\/$/,'');this.key=key;this.fetcher=fetcher;this.cache=new Map();}
 async request(path,{token,body,method=body?'POST':'GET'}={}){const response=await this.fetcher(this.url+path,{method,headers:{apikey:this.key,...(token?{Authorization:`Bearer ${token}`} : {}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!response.ok)throw new HttpError(response.status===401||response.status===403?401:503,response.status===401||response.status===403?'Acesso recusado. Entre novamente.':'Supabase indisponível ou configuração incompleta.');return response.status===204?null:response.json();}
 async login(data,refresh=false){if(refresh?typeof data.refresh_token!=='string'||data.refresh_token.length>4096:typeof data.email!=='string'||data.email.length>320||typeof data.password!=='string'||data.password.length>1024)throw new HttpError(400,'Dados de acesso inválidos.');try{const value=await this.request(`/auth/v1/token?grant_type=${refresh?'refresh_token':'password'}`,{body:refresh?{refresh_token:data.refresh_token}:{email:data.email,password:data.password}});const access=await this.authenticate(`Bearer ${value.access_token}`);return{allowedMapIds:[...access.maps],access_token:value.access_token,refresh_token:value.refresh_token,expires_in:value.expires_in,user:{id:value.user.id,email:value.user.email}};}catch{throw new HttpError(401,refresh?'Sessão expirada. Entre novamente.':'Não foi possível entrar. Confira seu acesso.');}}
 async authenticate(header){if(typeof header!=='string'||!header.startsWith('Bearer ')||header.length>12000)throw new HttpError(401,'Login necessário.');const token=header.slice(7),hash=createHash('sha256').update(token).digest('hex'),cached=this.cache.get(hash);if(cached&&cached.until>Date.now())return cached.value;
  const user=await this.request('/auth/v1/user',{token});if(typeof user.id!=='string')throw new HttpError(401,'Usuário inválido.');const rows=await this.request('/rest/v1/twin_map_access?select=map_id',{token});if(!Array.isArray(rows))throw new HttpError(503,'Permissões indisponíveis.');const value={userId:user.id,token,maps:new Set(rows.map(r=>r.map_id))};let expires=0;try{expires=JSON.parse(Buffer.from(token.split('.')[1],'base64url').toString()).exp*1000;}catch{}const until=Math.min(Date.now()+30000,expires||Date.now());for(const [key,c] of this.cache)if(c.until<=Date.now())this.cache.delete(key);if(this.cache.size<1000)this.cache.set(hash,{value,until});return value;
 }
 async logout(user){this.cache.delete(createHash('sha256').update(user.token).digest('hex'));await this.request('/auth/v1/logout?scope=local',{token:user.token,method:'POST'});}
 async list(mapId,user){const rows=await this.request(`/rest/v1/twin_sessions?map_id=eq.${encodeURIComponent(mapId)}&select=payload&order=started_at.asc&limit=10`,{token:user.token});if(!Array.isArray(rows))throw new HttpError(503,'Histórico inválido.');return rows.map(r=>r.payload);}
 async save(session,user){await this.request('/rest/v1/rpc/twin_save_session',{token:user.token,body:{p_map_id:session.mapId,p_session:session}});}
}
