import {waitForBackend} from './backendHealth';
import {useEffect,useState,type ReactNode} from 'react';
import {authToken,clearAuth,getAuthSession,login,prepareLogout,subscribeAuth} from './auth';
const base=(import.meta.env.VITE_BACKEND_URL||'').replace(/\/$/,'');
export function AuthGate({children}:{children:ReactNode}){
 const [auth,setAuth]=useState(getAuthSession),[required,setRequired]=useState<boolean|null>(base?null:false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>subscribeAuth(()=>setAuth(getAuthSession())),[]);
 useEffect(()=>{if(!base)return;let active=true;const abort=new AbortController();waitForBackend(base,abort.signal).then(data=>{if(active){setRequired(data.authRequired);setError('');}}).catch(err=>{if(active)setError(err instanceof Error?err.message:'Falha de conexão.');});return()=>{active=false;abort.abort();};},[retry]);
 if(required===false)return <>{children}</>;
 if(required===null)return <main className="auth-card"><h1>{error?'Não foi possível conectar':'Conectando ao servidor'}</h1><p>{error?'O servidor pode estar iniciando ou temporariamente indisponível.':'Aguardando o servidor. Tentaremos novamente automaticamente por até 90 segundos.'}</p>{error&&<p role="alert">{error}</p>}{error&&<button onClick={()=>{setError('');setRetry(n=>n+1);}}>Tentar novamente</button>}</main>;
 if(!auth)return <main className="auth-card"><h1>Entrar no Operational Twin</h1><p>Acesso às localidades autorizadas. A sessão de login fica somente nesta aba; recarregar exige entrar novamente.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await login(base,email,password);setPassword('');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label>E-mail<input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy}>{busy?'Entrando…':'Entrar'}</button></form>{error&&<p role="alert">{error}</p>}<p>Sem acesso? Solicite cadastro e permissão ao responsável pelo projeto.</p></main>;
 return <><div className="auth-strip"><span>{auth.user.email||'Usuário autenticado'}</span><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await prepareLogout();const token=await authToken(base,auth.user.id);await fetch(base+'/auth/logout',{method:'POST',headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(10000)}).catch(()=>{});clearAuth();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}>{busy?'Encerrando e salvando…':'Sair'}</button>{error&&<span role="alert">{error} <button onClick={()=>{clearAuth();setError('');}}>Sair sem salvar</button></span>}</div><div key={auth.user.id}>{children}</div></>;
}
