export type AuthSession={access_token:string;refresh_token:string;expires_at:number;allowedMapIds:string[];user:{id:string;email?:string}};
let session:AuthSession|null=null,epoch=0,refreshing:Promise<void>|null=null;
const listeners=new Set<()=>void>(),beforeLogout=new Set<()=>Promise<void>>();
export const getAuthSession=()=>session;
export const canAccessMap=(id:string)=>!session||session.allowedMapIds.includes(id);
export const authOwner=()=>session?.user.id;
export const subscribeAuth=(fn:()=>void)=>{listeners.add(fn);return()=>{listeners.delete(fn);};};
export const registerBeforeLogout=(fn:()=>Promise<void>)=>{beforeLogout.add(fn);return()=>{beforeLogout.delete(fn);};};
export async function prepareLogout(){await Promise.all([...beforeLogout].map(fn=>fn()));}
export function clearAuth(){epoch++;session=null;refreshing=null;listeners.forEach(fn=>fn());}
export function acceptAuth(value:unknown){const data=value as {access_token?:string;refresh_token?:string;expires_in?:number;allowedMapIds?:string[];user?:{id:string;email?:string}};if(!data||typeof data.access_token!=='string'||typeof data.refresh_token!=='string'||typeof data.expires_in!=='number'||data.expires_in<=0||typeof data.user?.id!=='string'||!Array.isArray(data.allowedMapIds)||!data.allowedMapIds.every(id=>typeof id==='string'))throw new Error('Resposta de login inválida.');session={access_token:data.access_token,refresh_token:data.refresh_token,expires_at:Date.now()+data.expires_in*1000,allowedMapIds:data.allowedMapIds,user:data.user};listeners.forEach(fn=>fn());}
export async function login(base:string,email:string,password:string){const current=++epoch;const response=await fetch(base+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password}),signal:AbortSignal.timeout(90000)});if(current!==epoch)throw new Error('Login cancelado.');if(!response.ok)throw new Error('Não foi possível entrar. Confira os dados e a disponibilidade do servidor.');const value=await response.json();if(current!==epoch)throw new Error('Login cancelado.');acceptAuth(value);}
export async function authToken(base:string,expectedOwner?:string){if(expectedOwner&&session?.user.id!==expectedOwner)throw new Error('Sessão de usuário alterada.');if(!session)return undefined;if(session.expires_at-Date.now()<60000){if(!refreshing){const current=epoch,refresh_token=session.refresh_token;refreshing=(async()=>{const response=await fetch(base+'/auth/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token}),signal:AbortSignal.timeout(20000)});if(current!==epoch)throw new Error('Sessão alterada.');if(!response.ok)throw new Error('Sessão expirada. Saia e entre novamente.');const value=await response.json();if(current!==epoch)throw new Error('Sessão alterada.');acceptAuth(value);})().finally(()=>{if(current===epoch)refreshing=null;});}await refreshing;}if(expectedOwner&&session?.user.id!==expectedOwner)throw new Error('Sessão de usuário alterada.');return session?.access_token;}
