import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mapLoader,type MapMetrics} from '../maps/MapLoader';
import type {OperationalMap,Vec3} from '../../types/maps';
import {disposeObject} from '../../utils/three/dispose';
export class TwinWorld {
 readonly scene=new THREE.Scene();readonly camera=new THREE.PerspectiveCamera(50,1,.1,100000);readonly renderer:THREE.WebGLRenderer;readonly controls:OrbitControls;
 readonly overlays=new THREE.Group();root:THREE.Group|null=null;box=new THREE.Box3();extent=1; private frame=0;private disposed=false;private observer:ResizeObserver;private down={x:0,y:0};private fpsSamples:number[]=[];private frames=0;private last=performance.now();
 onError:(message:string)=>void=()=>{};
 onPick:(p:Vec3,name:string)=>void=()=>{};onMetrics:(data:Record<string,number>)=>void=()=>{};
 constructor(readonly host:HTMLDivElement){this.scene.background=new THREE.Color('#0b1720');this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));host.appendChild(this.renderer.domElement);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.scene.add(new THREE.HemisphereLight(0xffffff,0x82909b,2),this.overlays);this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.resize();this.renderer.domElement.addEventListener('webglcontextlost',this.contextLost);this.renderer.domElement.addEventListener('pointerdown',this.pointerDown);this.renderer.domElement.addEventListener('pointerup',this.pointerUp);this.render();}
 private contextLost=(e:Event)=>{e.preventDefault();cancelAnimationFrame(this.frame);this.onError('Contexto WebGL perdido. Tente carregar novamente.');};
 private pointerDown=(e:PointerEvent)=>{this.down={x:e.clientX,y:e.clientY};};
 private pointerUp=(e:PointerEvent)=>{if(e.button!==0||Math.hypot(e.clientX-this.down.x,e.clientY-this.down.y)>5||!this.root)return;const rect=this.renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),this.camera);const hit=ray.intersectObject(this.root,true)[0];if(hit)this.onPick({x:hit.point.x,y:hit.point.y,z:hit.point.z},hit.object.name);};
 private resize(){const w=Math.max(1,this.host.clientWidth),h=Math.max(1,this.host.clientHeight);this.renderer.setSize(w,h);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 private render=()=>{if(this.disposed)return;this.controls.update();this.renderer.render(this.scene,this.camera);this.frames++;const now=performance.now();if(now-this.last>=1000){const fps=Math.round(this.frames*1000/(now-this.last));this.fpsSamples.push(fps);if(this.fpsSamples.length>60)this.fpsSamples.shift();const heap=(performance as Performance & {memory?:{usedJSHeapSize:number}}).memory;this.onMetrics({fps,averageFps:Math.round(this.fpsSamples.reduce((a,b)=>a+b,0)/this.fpsSamples.length),...(heap?{jsHeapMiB:Math.round(heap.usedJSHeapSize/1048576)}:{}),drawCalls:this.renderer.info.render.calls,renderTriangles:this.renderer.info.render.triangles,gpuGeometries:this.renderer.info.memory.geometries,gpuTextures:this.renderer.info.memory.textures});this.frames=0;this.last=now;}this.frame=requestAnimationFrame(this.render);};
 async load(map:OperationalMap,onProgress:(s:string)=>void):Promise<MapMetrics|null>{const result=await mapLoader.load(map,onProgress);if(this.disposed||!result)return null;this.root=result.root;this.scene.add(result.root);this.box.setFromObject(result.root);this.extent=Math.max(...this.box.getSize(new THREE.Vector3()).toArray());this.camera.near=Math.max(.01,this.extent/10000);this.camera.far=this.extent*30;this.camera.updateProjectionMatrix();this.home();if(map.initialCamera){this.camera.position.copy(map.initialCamera.position);this.controls.target.copy(map.initialCamera.target);}return result.metrics;}
 setQuality(ratio:number){this.renderer.setPixelRatio(Math.min(devicePixelRatio,ratio));this.resize();}
 get maxY(){return this.box.max.y;}
 home(top=false){if(this.box.isEmpty())return;const center=this.box.getCenter(new THREE.Vector3()),size=this.box.getSize(new THREE.Vector3());const halfFov=Math.min(this.camera.fov*Math.PI/360,Math.atan(Math.tan(this.camera.fov*Math.PI/360)*this.camera.aspect));const distance=size.length()*.5/Math.sin(halfFov)*1.04;this.controls.target.copy(center);this.camera.position.copy(center).add((top?new THREE.Vector3(0,1,.001):new THREE.Vector3(.6,.8,.8)).normalize().multiplyScalar(distance));this.controls.minDistance=this.extent*.02;this.controls.maxDistance=this.extent*10;this.controls.update();}

 surface(u:number,v:number):Vec3|null{if(!this.root)return null;const x=THREE.MathUtils.lerp(this.box.min.x,this.box.max.x,u),z=THREE.MathUtils.lerp(this.box.min.z,this.box.max.z,v);const ray=new THREE.Raycaster(new THREE.Vector3(x,this.box.max.y+this.extent,z),new THREE.Vector3(0,-1,0));const p=ray.intersectObject(this.root,true)[0]?.point;return p?{x:p.x,y:p.y,z:p.z}:null;}
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.observer.disconnect();this.controls.dispose();this.renderer.domElement.removeEventListener('webglcontextlost',this.contextLost);this.renderer.domElement.removeEventListener('pointerdown',this.pointerDown);this.renderer.domElement.removeEventListener('pointerup',this.pointerUp);disposeObject(this.overlays);mapLoader.clear();this.root=null;this.renderer.renderLists.dispose();this.renderer.dispose();this.renderer.forceContextLoss();this.renderer.domElement.remove();this.scene.clear();}
}
